apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: limited-user-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: limited-user-binding
  namespace: default
subjects:
  - kind: User
    name: limited-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: limited-user-role
  apiGroup: rbac.authorization.k8s.io
